---
- hosts: localhost
  become_user: sudo

  roles:
    - gui
    - programming
    - productivity

  tasks:
    - name: Install the nvidia drivers
      pacman:
        name:
          - nvidia
          - nvidia-settings

    - name: Ensure that right clicks work on the touchpad
      dconf:
        key: "/org/gnome/desktop/peripherals/touchpad/click-method"
        value: "'areas'"
      become: yes
      become_user: "{{ user_name }}"
