---
- name: Install neovim
  package: name=neovim state=present

- name: Install vim-plug
  get_url: "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
  dest: "{{ user_home }}/.config/nvim/autoload/plug.vim"
