---
- name: Install xorg
  pacman:
    name:
      - xorg-server
      - xf86-input-libinput
      - xorg-xinput

- name: Ensure synaptics is not installed, since it can cause issues with the touchpad
  pacman: "name=xf86-input-synaptics state=absent"

- name: Install gnome + gnome tools.
  pacman:
   name:
      - gdm
      - gnome
      - gnome-extra
      - gnome-shell
      - gnome-tweak-tool

- name: Enable gdbm service
  service: "name=gdm enabled=yes"

- name: Ensure icons are shown in menus.
  dconf:
    key: "/org/gnome/settings-daemon/plugins/xsettings/overrides"
    value: "{'Gtk/ButtonImages': <1>, 'Gtk/MenuImages': <1>}"
  become: yes
  become_user: "{{ user_name }}"

- name: Deactivate tracker monitor
  dconf:
    key: "/org/freedesktop/tracker/miner/files/enable-monitors"
    value: "false"
  become: yes
  become_user: "{{ user_name }}"

- name: Deactivate tracker interval
  dconf:
    key: "/org/freedesktop/tracker/miner/files/crawling-interval"
    value: "-2"
  become: yes
  become_user: "{{ user_name }}"
