---
- name: Install build dependencies and build tools.
  pacman:
    name:
      - base-devel
      - gdb
      - clang
      - clang-tools-extra
      - cmake
      - make ninja
      - valgrind

- name: Install SCMs and dependencies for their guis.
  pacman:
    name:
      - git
      - subversion
      - tk

- name: Install Qt
  pacman:
    name:
      - qt5-base
      - qt5-doc
      - qt5-examples

- name: Install Python
  pacman:
    name:
      - jupyter_console
      - python
      - python-pip
      - python2
      - python2-pip

- name: Install Rust
  pacman:
    name:
      - rust
      - rust-racer
      - rust-docs

- name: Install JVM Languages and Environment
  pacman:
    name:
      - apache-ant
      - clojure
      - gradle
      - groovy
      - kotlin
      - maven
      - sbt
      - scala

- name: Install IDEs
  pacman:
    name:
      - intellij-idea-community-edition
      - qtcreator

- name: Install Container and Virtualization
  pacman:
    name:
      - docker
      - docker-compose
      - libvirt
      - qemu

- name: Add user to groups so that they can use containers and virtualization
  user:
    name: "{{ user_name }}"
    groups:
      - docker
    append: yes

- name: Enable docker service
  service: "name=docker enabled=yes"
